export const nilChainInfo = {
    chainId: "nillion-chain-testnet-1",
    chainName: "Nillion Testnet",
    rpc: "https://testnet-nillion-rpc.lavenderfive.com",
    rest: "https://testnet-nillion-api.lavenderfive.com",
    nodeProvider: {
      name: "Lavender.Five",
      email: "hello@lavenderfive.com",
      website: "https://www.lavenderfive.com/",
    },
    chainSymbolImageUrl: "https://raw.githubusercontent.com/chainapsis/keplr-chain-registry/main/images/nillion-chain-testnet/nil.png",
    bip44: { coinType: 118 },
    bech32Config: {
      bech32PrefixAccAddr: 'nillion',
      bech32PrefixAccPub: 'nillionpub',
      bech32PrefixValAddr: 'nillionvaloper',
      bech32PrefixValPub: 'nillionvaloperpub',
      bech32PrefixConsAddr: 'nillionvalcons',
      bech32PrefixConsPub: 'nillionvalconspub',
    },
    currencies: [{ coinDenom: 'NIL', coinMinimalDenom: 'unil', coinDecimals: 6 }],
    feeCurrencies: [{ coinDenom: 'NIL', coinMinimalDenom: 'unil', coinDecimals: 6 }],
    stakeCurrency: { coinDenom: 'NIL', coinMinimalDenom: 'unil', coinDecimals: 6 },
    coinType: 118,
  };